networks:
  webapp-network:
    driver: bridge

services:
  restapi:
    build:
      context: ./
      dockerfile: Dockerfile.local
    image: node:18-alpine
    working_dir: /usr/src/restapi
    container_name: restapi
    networks:
      - webapp-network
    ports:
      - 3002:3000
    volumes:
      - ./:/usr/src/restapi:rw
    command: "yarn start:dev"
